FROM node:22-alpine

WORKDIR /app

# Instala dependencias una sola vez en la imagen base de desarrollo
COPY frontend/package*.json ./
RUN npm ci

EXPOSE 4200

CMD ["npm", "run", "start", "--", "--host", "0.0.0.0", "--port", "4200", "--poll", "2000"]
