// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFF5Ci99VUFgiLYfkHELq0OYTZaSoUct4',
    appId: '1:169164208305:web:299ad02b7cfd5efd3d0a90',
    messagingSenderId: '169164208305',
    projectId: 'ceroespera-88bc0',
    authDomain: 'ceroespera-88bc0.firebaseapp.com',
    storageBucket: 'ceroespera-88bc0.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqzUL39wm_RS0hCJgzuFoJ5DAOjszjrmk',
    appId: '1:169164208305:android:e02d072e957f7a233d0a90',
    messagingSenderId: '169164208305',
    projectId: 'ceroespera-88bc0',
    storageBucket: 'ceroespera-88bc0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBA3RqU7fYlStjysnqXckgqiAeqEagtt2k',
    appId: '1:169164208305:ios:15e58d2f804e0f3c3d0a90',
    messagingSenderId: '169164208305',
    projectId: 'ceroespera-88bc0',
    storageBucket: 'ceroespera-88bc0.firebasestorage.app',
    iosBundleId: 'com.example.mobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBA3RqU7fYlStjysnqXckgqiAeqEagtt2k',
    appId: '1:169164208305:ios:15e58d2f804e0f3c3d0a90',
    messagingSenderId: '169164208305',
    projectId: 'ceroespera-88bc0',
    storageBucket: 'ceroespera-88bc0.firebasestorage.app',
    iosBundleId: 'com.example.mobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAFF5Ci99VUFgiLYfkHELq0OYTZaSoUct4',
    appId: '1:169164208305:web:f78b0821e69fd2e33d0a90',
    messagingSenderId: '169164208305',
    projectId: 'ceroespera-88bc0',
    authDomain: 'ceroespera-88bc0.firebaseapp.com',
    storageBucket: 'ceroespera-88bc0.firebasestorage.app',
  );
}
